name: todo_task_manager
description: A comprehensive Todo Task Management Mobile App with social authentication and innovative features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Local Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Authentication
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  google_sign_in: ^6.1.6
  
  # UI & Animations
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.3.0
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1
  
  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  
  # Networking & Crash Reporting
  http: ^1.1.2
  firebase_crashlytics: ^3.4.9
  
  # Voice & AI Features
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  
  # Biometrics
  local_auth: ^2.1.7
  
  # Icons & UI
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
  #   - assets/animations/
  #   - assets/icons/
  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
